CREATE TABLE IF NOT EXISTS GENRE (
    NAME VARCHAR(50) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS THEME (
    NAME VARCHAR(50) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS PLAYLIST (
    NAME VARCHAR(50) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS CLIENT (
    CLIENT_NUMBER BIGINT PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL_ADDRESS VARCHAR(50) NOT NULL,
    PHONE_NUMBER INT NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYEE (
    ID BIGINT PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CD (
    CD_NUMBER BIGINT PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    PRODUCER VARCHAR(50) NOT NULL,
    YEAR INT NOT NULL,
    COPIES INT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATION (
    ID BIGINT PRIMARY KEY,
    STREET VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    POSTAL_CODE INT NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    COMMENT VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS MANAGER (
    ID BIGINT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS EVENTPLANNER (
    ID BIGINT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS DJ (
    ID BIGINT PRIMARY KEY,
    FOREIGN KEY (ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE IF NOT EXISTS SONG (
    CD_NUMBER BIGINT,
    TRACK_NUMBER INT,
    TITLE VARCHAR(50) NOT NULL,
    ARTIST VARCHAR(50) NOT NULL,
    DURATION INT NOT NULL,
    GENRE_NAME VARCHAR(50),
    PRIMARY KEY (CD_NUMBER, TRACK_NUMBER),
    FOREIGN KEY (CD_NUMBER) REFERENCES CD(CD_NUMBER),
    FOREIGN KEY (GENRE_NAME) REFERENCES GENRE(NAME)
);

CREATE TABLE IF NOT EXISTS EVENT (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(200),
    CLIENT_ID BIGINT,
    MANAGER_ID BIGINT,
    EVENT_PLANNER_ID BIGINT,
    DJ_ID BIGINT,
    THEME_NAME VARCHAR(50),
    LOCATION_ID BIGINT,
    RENTAL_FEE INT,
    PLAYLIST_NAME VARCHAR(50),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_NUMBER),
    FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER(ID),
    FOREIGN KEY (EVENT_PLANNER_ID) REFERENCES EVENTPLANNER(ID),
    FOREIGN KEY (DJ_ID) REFERENCES DJ(ID),
    FOREIGN KEY (THEME_NAME) REFERENCES THEME(NAME),
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(ID),
    FOREIGN KEY (PLAYLIST_NAME) REFERENCES PLAYLIST(NAME)
);

CREATE TABLE IF NOT EXISTS REQUEST (
    NAME VARCHAR(50) PRIMARY KEY,
    EVENT_ID BIGINT,
    PROVIDER VARCHAR(50) NOT NULL,
    PRICE INT NOT NULL,
    FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID)
);

CREATE TABLE IF NOT EXISTS CONTAINS (
    PLAYLIST_NAME VARCHAR(50),
    CD_NUMBER BIGINT,
    TRACK_NUMBER INT,
    PRIMARY KEY (PLAYLIST_NAME, CD_NUMBER, TRACK_NUMBER),
    FOREIGN KEY (PLAYLIST_NAME) REFERENCES PLAYLIST(NAME),
    FOREIGN KEY (CD_NUMBER, TRACK_NUMBER) REFERENCES SONG(CD_NUMBER, TRACK_NUMBER)
);

CREATE TABLE IF NOT EXISTS SPECIALIZATION (
    DJ_ID BIGINT,
    GENRE_NAME VARCHAR(50),
    PRIMARY KEY (DJ_ID, GENRE_NAME),
    FOREIGN KEY (DJ_ID) REFERENCES DJ(ID),
    FOREIGN KEY (GENRE_NAME) REFERENCES GENRE(NAME)
);

CREATE TABLE IF NOT EXISTS SPECIALIZES (
    GENRE_NAME VARCHAR(50),
    SUBGENRE_NAME VARCHAR(50),
    PRIMARY KEY (GENRE_NAME, SUBGENRE_NAME),
    FOREIGN KEY (GENRE_NAME) REFERENCES GENRE(NAME),
    FOREIGN KEY (SUBGENRE_NAME) REFERENCES GENRE(NAME)
);

CREATE TABLE IF NOT EXISTS SUITABLEFOR (
    THEME_NAME VARCHAR(50),
    PLAYLIST_NAME VARCHAR(50),
    PRIMARY KEY (THEME_NAME, PLAYLIST_NAME),
    FOREIGN KEY (THEME_NAME) REFERENCES THEME(NAME),
    FOREIGN KEY (PLAYLIST_NAME) REFERENCES PLAYLIST(NAME)
);

CREATE TABLE IF NOT EXISTS SUPERVISION (
    SUPERVISOR_ID BIGINT,
    EMPLOYEE_ID BIGINT,
    PRIMARY KEY (SUPERVISOR_ID, EMPLOYEE_ID),
    FOREIGN KEY (SUPERVISOR_ID) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);